apiVersion: v1
kind: Service
metadata:
  labels:
    service: cast-service
  name: cast-service
spec:
  ports:
  - name: "8002"
    port: 8002
    nodePort: {{ .Values.castnodeport }}
    targetPort: 8000
  selector:
    service: cast-service
  type: NodePort
