apiVersion: v1
kind: PersistentVolume
metadata:
  name: cast-service-pv-{{ .Values.mount }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/{{ .Values.mount }}/Jenkins_devops_exams/cast-service/"
  storageClassName: local-path
