apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: cast-service-pvc
  name: cast-service-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
