apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    service: movie-service
  name: movie-service
spec:
  ports:
  - name: "8001"
    port: 8001
    nodePort: {{ .Values.movienodeport }}
    targetPort: 8000
  selector:
    service: movie-service
  type: NodePort