apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        service: nginx
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: ""
        name: nginx
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/
          name: nginx-pv-{{ .Values.mount }}
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: nginx-pv-{{ .Values.mount }}
        persistentVolumeClaim:
          claimName: nginx-pvc
