apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-{{ .Values.mount }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/{{ .Values.mount }}/Jenkins_devops_exams/data/"
  storageClassName: local-path


  
